package br.edu.ufcg.dsc.util;

public enum ResultData {
	TEMPO_TOTAL, TEMPO_COMPILACAO_PRODUTOS, TEMPO_COMPILACAO_TESTES, TEMPO_EXECUCAO_TESTES, 
	QUANTIDADE_TESTES, QUANTIDADE_PRODUTOS_COMPILADOS, IS_REFINEMENT;
}
