
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 04 17:09:42 GMT-03:00 2010
//----------------------------------------------------

package br.edu.ufcg.dsc.ck.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPAREN = 3;
  public static final int NOT = 6;
  public static final int AND = 5;
  public static final int error = 1;
  public static final int LPAREN = 2;
  public static final int OR = 4;
  public static final int EOF = 0;
  public static final int FEATURE = 7;
}

